apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: argcron
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-container
              image: vishnuhdadhich/python-arg-test
              args:
              - arg.py
              - six
              - something
              - five
          restartPolicy: OnFailure
