apiVersion: batch/v1
kind: Job
metadata:
  name: hellojob
spec:
  template:
    spec:
      containers:
        - name: container-job
          image: vishnuhdadhich/python-arg-test
          args:
          - hello.py
      restartPolicy: OnFailure
